title: digitallab-hshl project page
logo: /assets/img/logo.png
description: Lightweight remote solution for microcontroller class.
show_downloads: true
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0

